version: '2'
services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    tty: true
    networks:
      my_network:
        ipv4_address: 192.168.1.100


  dhcp:
    build:
      context: ./dhcp
      dockerfile: Dockerfile
    tty: true
    networks:
      my_network:
        ipv4_address: 192.168.1.101


networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

