version: '2'
services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    tty: true
    hostname: dns
    domainname: dnsserver.io
   #ports:
   #- "53:53/udp"
   #- "53:53/tcp"
   #- "10000:10000/tcp"
    networks:
      my_network:
        ipv4_address: 192.168.1.100


  dhcp:
    build:
      context: ./dhcp
      dockerfile: Dockerfile
    tty: true
    networks:
      my_network:
        ipv4_address: 192.168.1.101
  
  host1:
    build:
      context: ./host1
      dockerfile: Dockerfile
    tty: true
    networks:
      my_network:
        ipv4_address: 192.168.1.1

  host2:
    build:
      context: ./host2
      dockerfile: Dockerfile
    tty: true
    networks:
      my_network:
        ipv4_address: 192.168.1.2
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

